# Install pre-commit hooks via
# pre-commit install

exclude: >
    (?x)^(
      \.vscode/settings\.json
    )$

repos:

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: check-json
    - id: check-yaml
      exclude: >
        (?x)^(
          {{cookiecutter.project_name}}/.github/workflows/ci.yml
        )$
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: flake8

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      exclude: >
        (?x)^(
          {{cookiecutter.project_name}}/tests/test_basic.py
        )$
